messages:
  - schema: "path/to/schema.json"
    constants:
      - name: dotted.path
        value: 1.2
      - name: other.field
        value: Hello World
    variables:
      - name: dotted.path
        generator:
          numeric-generator:
            base: 100
            amp: 10