client:
  type: mqtt
  config:
    topic: "test"
    broker: "tcp://localhost:1886"
    qos: 0
kafka:
  topic: "test"
  partition: 1
  max-bytes: 1000
  brokers: ["http://localhost:9092"]
workload:
  preset: smoke
  vu: 100
  max-size: 10000 #10KB
collector:
  file: "test-configs/example.csv"
  flush: 1s

