client:
  type: mqtt
  config:
    topic: "wearables-raw"
    broker: "tcp://localhost:1886"
execution:
  preset: smoke
  collector: "./csv/heart-rate.csv"
messages:
  test:
    request:
      schema: "test-resources/app-message.json"
      constants:
        - name: "deviceInfo.platform"
          value: "iOS"
        - name: "deviceInfo.deviceId"
          value: "unknown_device"
        - name: "deviceInfo.authorizationToken"
